# Configuración para Postgres
changelog-file: changelog.xml
url: jdbc:postgresql://postgres_container:5432/postgres
username: postgres
password: root
driver: org.postgresql.Driver
# Al estar en la misma carpeta, Liquibase lo encontrará automáticamente
classpath: /liquibase/workspace/postgresql.jar