services:
  db:
    image: postgres:latest
    container_name: postgres_cafetin
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sena_adso
      - POSTGRES_DB=cafetin_sena
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: