spring.datasource.url=jdbc:postgresql://localhost:5432/coffee-shop
spring.datasource.username=sharith
spring.datasource.password=1830

# Configuración de JPA para PostgreSQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect